const { NotFoundError, ValidationError, AuthorizationError } = require('../../../utils/errorHandler');
const { roundCurrency } = require('../../../services/creditFormulaHelpers');

const normalizeAttachmentVisibility = (value) => {
  if (typeof value === 'boolean') {
    return value;
  }

  if (typeof value === 'string') {
    return ['true', '1', 'yes', 'on'].includes(value.trim().toLowerCase());
  }

  return false;
};

const escapePdfText = (value) => String(value)
  .replaceAll('\\', '\\\\')
  .replaceAll('(', '\\(')
  .replaceAll(')', '\\)');

const buildPdfTextStream = ({ title, lines }) => {
  const commands = [
    'BT',
    '/F1 18 Tf',
    '50 780 Td',
    `(${escapePdfText(title)}) Tj`,
    '0 -28 Td',
    '/F1 12 Tf',
  ];

  lines.forEach((line, index) => {
    if (index > 0) {
      commands.push('0 -18 Td');
    }
    commands.push(`(${escapePdfText(line)}) Tj`);
  });

  commands.push('ET');
  return commands.join('\n');
};

const buildPdfBuffer = ({ title, lines }) => {
  const contentStream = buildPdfTextStream({ title, lines });
  const objects = [
    '1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj',
    '2 0 obj\n<< /Type /Pages /Count 1 /Kids [3 0 R] >>\nendobj',
    '3 0 obj\n<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>\nendobj',
    '4 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>\nendobj',
    `5 0 obj\n<< /Length ${Buffer.byteLength(contentStream, 'utf8')} >>\nstream\n${contentStream}\nendstream\nendobj`,
  ];

  let pdf = '%PDF-1.4\n';
  const offsets = [0];

  objects.forEach((object) => {
    offsets.push(Buffer.byteLength(pdf, 'utf8'));
    pdf += `${object}\n`;
  });

  const xrefOffset = Buffer.byteLength(pdf, 'utf8');
  pdf += `xref\n0 ${objects.length + 1}\n`;
  pdf += '0000000000 65535 f \n';
  offsets.slice(1).forEach((offset) => {
    pdf += `${String(offset).padStart(10, '0')} 00000 n \n`;
  });
  pdf += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefOffset}\n%%EOF`;

  return Buffer.from(pdf, 'utf8');
};

const buildPromiseToPayPdfBuffer = ({ promise, loan, customer }) => {
  const formatDate = (date) => {
    if (!date) return '-';
    return new Date(date).toLocaleDateString('en-IN', {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
    });
  };

  const formatCurrency = (amount) => `₹${Number(amount || 0).toFixed(2)}`;

  return buildPdfBuffer({
    title: 'PROMISE TO PAY RECEIPT',
    lines: [
      `Document ID: ${promise.id}`,
      `Date: ${formatDate(promise.createdAt)}`,
      '',
      '=== LOAN DETAILS ===',
      `Loan ID: ${loan.id}`,
      `Loan Amount: ${formatCurrency(loan.amount)}`,
      `Customer: ${customer.name}`,
      `Customer Email: ${customer.email}`,
      '',
      '=== PROMISE DETAILS ===',
      `Promised Payment Date: ${formatDate(promise.promisedDate)}`,
      `Promised Amount: ${formatCurrency(promise.amount)}`,
      `Status: ${promise.status?.toUpperCase() || 'PENDING'}`,
      promise.notes ? `Notes: ${promise.notes}` : '',
      '',
      '=== PAYMENT TERMS ===',
      'This document serves as official acknowledgment of the promise to pay.',
      'The customer agrees to make the payment by the specified date.',
      'Failure to comply may result in collection proceedings.',
      '',
      '=== SIGNATURES ===',
      '',
      'Customer Signature: ________________________',
      `Date: ${formatDate(promise.promisedDate)}`,
      '',
      'Authorized Agent: ________________________',
      `Date: ${formatDate(promise.createdAt)}`,
      '',
      '---',
      'Generated by LendFlow Loan Management System',
    ].filter(Boolean),
  });
};

const formatCalendarEntryStatus = ({ row, isOverdue, outstandingAmount }) => {
  if (outstandingAmount <= 0.01) {
    return 'paid';
  }

  if (isOverdue) {
    return 'overdue';
  }

  if ((row.paidTotal || 0) > 0) {
    return 'partial';
  }

  return 'pending';
};

const buildCalendarEntries = ({ schedule, alerts }) => {
  const activeAlertByInstallment = new Map(
    alerts
      .filter((alert) => alert.status === 'active')
      .map((alert) => [Number(alert.installmentNumber), alert]),
  );

  const alertByInstallment = new Map(
    alerts
      .map((alert) => [Number(alert.installmentNumber), alert]),
  );

  return schedule.map((row) => {
    if (row.status === 'annulled') {
      return {
        installmentNumber: row.installmentNumber,
        dueDate: row.dueDate,
        scheduledPayment: roundCurrency(row.scheduledPayment || 0),
        remainingPrincipal: roundCurrency(row.remainingPrincipal || 0),
        remainingInterest: roundCurrency(row.remainingInterest || 0),
        outstandingAmount: 0,
        status: 'annulled',
        alertId: null,
      };
    }

    const outstandingAmount = roundCurrency((row.remainingPrincipal || 0) + (row.remainingInterest || 0));
    const alert = activeAlertByInstallment.get(Number(row.installmentNumber)) || null;
    const isOverdue = Boolean(alert);

    return {
      installmentNumber: row.installmentNumber,
      dueDate: row.dueDate,
      scheduledPayment: roundCurrency(row.scheduledPayment || 0),
      remainingPrincipal: roundCurrency(row.remainingPrincipal || 0),
      remainingInterest: roundCurrency(row.remainingInterest || 0),
      outstandingAmount,
      status: formatCalendarEntryStatus({ row, isOverdue, outstandingAmount }),
      alertId: alertByInstallment.get(Number(row.installmentNumber))?.id || null,
    };
  });
};

/**
 * Create the use case that lists loans, optionally filtered through the shared access policy.
 * @param {{ loanRepository: object, loanAccessPolicy?: object }} dependencies
 * @returns {Function}
 */
const createListLoans = ({ loanRepository, loanAccessPolicy }) => async ({ actor }) => {
  const loans = await loanRepository.list();

  if (loanAccessPolicy) {
    return loanAccessPolicy.filterVisibleLoans({ actor, loans });
  }

  return loans;
};

/**
 * Create the use case that returns a canonical credit simulation preview.
 * @param {{ creditDomainService: object }} dependencies
 * @returns {Function}
 */
const createCreateSimulation = ({ creditDomainService }) => async (payload) => creditDomainService.simulate(payload);

/**
 * Create the use case that retrieves a single loan through the shared access policy.
 * @param {{ loanAccessPolicy?: object, loanRepository: object }} dependencies
 * @returns {Function}
 */
const createGetLoanById = ({ loanAccessPolicy, loanRepository }) => async ({ actor, loanId }) => {
  if (loanAccessPolicy) {
    return loanAccessPolicy.findAuthorizedLoan({ actor, loanId });
  }

  const loan = await loanRepository.findById(loanId);
  if (!loan) {
    throw new NotFoundError('Loan');
  }

  if (actor.role === 'customer' && loan.customerId !== actor.id) {
    throw new AuthorizationError('You can only view your own loans');
  }

  if (actor.role === 'agent' && loan.agentId !== actor.id) {
    throw new AuthorizationError('You can only view loans assigned to you');
  }

  return loan;
};

/**
 * Create the use case that persists a new loan while enforcing customer self-service boundaries.
 * @param {{ loanCreationService: object }} dependencies
 * @returns {Function}
 */
const createCreateLoan = ({ loanCreationService }) => async ({ actor, payload }) => {
  if (actor.role === 'customer' && Number(payload.customerId) !== actor.id) {
    throw new AuthorizationError('You can only create loans for your own customer record');
  }

  return loanCreationService.create(payload);
};

/**
 * Create the use case that lists loans for a customer and returns the owning customer record.
 * @param {{ customerRepository: object, loanRepository: object }} dependencies
 * @returns {Function}
 */
const createListLoansByCustomer = ({ customerRepository, loanRepository }) => async ({ actor, customerId }) => {
  if (actor.role === 'customer' && actor.id !== Number(customerId)) {
    throw new AuthorizationError('You can only view your own loans');
  }

  const customer = await customerRepository.findById(customerId);
  if (!customer) {
    throw new NotFoundError('Customer');
  }

  const loans = await loanRepository.listByCustomer(customerId);
  return { loans, customer };
};

/**
 * Create the use case that lists loans assigned to a specific agent.
 * @param {{ agentRepository: object, loanRepository: object }} dependencies
 * @returns {Function}
 */
const createListLoansByAgent = ({ agentRepository, loanRepository }) => async ({ actor, agentId }) => {
  if (actor.role === 'agent' && actor.id !== Number(agentId)) {
    throw new AuthorizationError('You can only view your own assigned loans');
  }

  const agent = await agentRepository.findById(agentId);
  if (!agent) {
    throw new NotFoundError('Agent');
  }

  const loans = await loanRepository.listByAgent(agentId);
  return { loans, agent };
};

/**
 * Create the use case that updates the primary loan lifecycle status.
 * @param {{ loanRepository: object, loanAccessPolicy?: object }} dependencies
 * @returns {Function}
 */
const createUpdateLoanStatus = ({ loanRepository, loanAccessPolicy }) => async ({ actor, loanId, status }) => {
  const validStatuses = ['pending', 'approved', 'rejected', 'active', 'closed', 'defaulted'];
  if (!validStatuses.includes(status)) {
    throw new ValidationError(`Invalid status. Must be one of: ${validStatuses.join(', ')}`);
  }

  const loan = loanAccessPolicy
    ? await loanAccessPolicy.findAuthorizedMutationLoan({ actor, loanId })
    : await loanRepository.findById(loanId);

  if (!loan) {
    throw new NotFoundError('Loan');
  }

  if (loan.status === 'closed' && status !== 'closed') {
    throw new ValidationError('Cannot modify a closed loan');
  }

  if (loan.status === 'rejected' && status !== 'rejected') {
    throw new ValidationError('Cannot modify a rejected loan');
  }

  loan.status = status;

  if (status === 'approved') {
    loan.startDate = new Date();
    const endDate = new Date();
    endDate.setMonth(endDate.getMonth() + loan.termMonths);
    loan.endDate = endDate;
  }

  if (status === 'defaulted') {
    loan.recoveryStatus = 'pending';
  }

  return loanRepository.save(loan);
};

/**
 * Create the use case that assigns an agent to a recoverable loan and emits a notification.
 * @param {{ loanRepository: object, agentRepository: object, userRepository: object, notificationPort: object }} dependencies
 * @returns {Function}
 */
const createAssignAgent = ({ loanRepository, agentRepository, userRepository, notificationPort }) => async ({ actor, loanId, agentId }) => {
  if (actor.role !== 'admin') {
    throw new AuthorizationError('Only admins can assign agents to loans');
  }

  const loan = await loanRepository.findById(loanId);
  if (!loan) {
    throw new NotFoundError('Loan');
  }

  const agent = await agentRepository.findById(agentId);
  if (!agent) {
    throw new NotFoundError('Agent');
  }

  if (!['approved', 'defaulted'].includes(loan.status)) {
    throw new ValidationError('Can only assign agents to approved or defaulted loans');
  }

  if (loan.agentId === agentId) {
    throw new ValidationError('This agent is already assigned to this loan');
  }

  loan.agentId = agentId;
  loan.recoveryStatus = loan.status === 'defaulted' ? 'assigned' : 'pending';
  const savedLoan = await loanRepository.save(loan);

  const user = await userRepository.findAgentUserByEmail(agent.email);
  if (user) {
    await notificationPort.sendAssignment(user.id, {
      loanId: savedLoan.id,
      loanAmount: savedLoan.amount,
      customerName: savedLoan.Customer?.name,
      customerEmail: savedLoan.Customer?.email,
      loanStatus: savedLoan.status,
      recoveryStatus: savedLoan.recoveryStatus,
      assignedBy: actor.id,
      assignedAt: new Date().toISOString(),
    });
  }

  return savedLoan;
};

/**
 * Create the use case that updates recovery state after policy and domain-guard validation.
 * @param {{ loanRepository: object, loanAccessPolicy?: object, recoveryStatusGuard?: object }} dependencies
 * @returns {Function}
 */
const createUpdateRecoveryStatus = ({ loanRepository, loanAccessPolicy, recoveryStatusGuard }) => async ({ actor, loanId, recoveryStatus }) => {
  const validRecoveryStatuses = ['pending', 'assigned', 'in_progress', 'contacted', 'negotiated', 'recovered', 'failed'];
  if (!validRecoveryStatuses.includes(recoveryStatus)) {
    throw new ValidationError(`Invalid recovery status. Must be one of: ${validRecoveryStatuses.join(', ')}`);
  }

  if (!['admin', 'agent'].includes(actor.role)) {
    throw new AuthorizationError('Only admins and agents can update recovery status');
  }

  const loan = loanAccessPolicy
    ? await loanAccessPolicy.findAuthorizedMutationLoan({ actor, loanId })
    : await loanRepository.findById(loanId);

  if (!loan) {
    throw new NotFoundError('Loan');
  }

  if (recoveryStatusGuard) {
    recoveryStatusGuard.assertCanTransition({ loan, nextRecoveryStatus: recoveryStatus });
  }

  loan.recoveryStatus = recoveryStatus;
  return loanRepository.save(loan);
};

/**
 * Create the use case that deletes rejected loans after access checks succeed.
 * @param {{ loanRepository: object, loanAccessPolicy?: object }} dependencies
 * @returns {Function}
 */
const createDeleteLoan = ({ loanRepository, loanAccessPolicy }) => async ({ actor, loanId }) => {
  if (actor.role === 'socio') {
    throw new AuthorizationError('Socio users cannot delete loans');
  }

  const loan = loanAccessPolicy
    ? await loanAccessPolicy.findAuthorizedLoan({ actor, loanId })
    : await loanRepository.findById(loanId);

  if (!loan) {
    throw new NotFoundError('Loan');
  }

  if (loan.status !== 'rejected') {
    throw new ValidationError('Only rejected loans can be deleted');
  }

  await loanRepository.destroy(loan);
};

/**
 * Create the use case that lists authorized loan attachments, filtering customer-visible rows when needed.
 * @param {{ attachmentRepository: object, loanAccessPolicy: object }} dependencies
 * @returns {Function}
 */
const createListLoanAttachments = ({ attachmentRepository, loanAccessPolicy }) => async ({ actor, loanId }) => {
  const loan = await loanAccessPolicy.findAuthorizedLoan({ actor, loanId });
  const attachments = await attachmentRepository.listByLoan(loan.id);

  if (actor.role === 'customer') {
    return attachments.filter((attachment) => attachment.customerVisible);
  }

  return attachments;
};

/**
 * Create the use case that persists metadata for a newly uploaded loan attachment.
 * @param {{ attachmentRepository: object, attachmentStorage: object, loanAccessPolicy: object }} dependencies
 * @returns {Function}
 */
const createCreateLoanAttachment = ({ attachmentRepository, attachmentStorage, loanAccessPolicy }) => async ({ actor, loanId, file, metadata = {} }) => {
  if (!file) {
    throw new ValidationError('Attachment file is required');
  }

  try {
    const loan = await loanAccessPolicy.findAuthorizedMutationLoan({ actor, loanId });

    return await attachmentRepository.create({
      loanId: loan.id,
      uploadedByUserId: actor.id,
      storageDisk: 'local',
      storagePath: attachmentStorage.toRelativePath(file.path),
      storedName: file.filename,
      originalName: file.originalname,
      mimeType: file.mimetype,
      sizeBytes: file.size,
      customerVisible: normalizeAttachmentVisibility(metadata.customerVisible),
      category: metadata.category ? String(metadata.category).trim() : null,
      description: metadata.description ? String(metadata.description).trim() : null,
    });
  } catch (error) {
    await attachmentStorage.deleteByAbsolutePath(file.path);
    throw error;
  }
};

/**
 * Create the use case that resolves a readable loan attachment for download.
 * @param {{ attachmentRepository: object, attachmentStorage: object, loanAccessPolicy: object }} dependencies
 * @returns {Function}
 */
const createDownloadLoanAttachment = ({ attachmentRepository, attachmentStorage, loanAccessPolicy }) => async ({ actor, loanId, attachmentId }) => {
  const loan = await loanAccessPolicy.findAuthorizedLoan({ actor, loanId });
  const attachment = await attachmentRepository.findByIdForLoan({ loanId: loan.id, attachmentId });

  if (!attachment) {
    throw new NotFoundError('Attachment');
  }

  if (actor.role === 'customer' && !attachment.customerVisible) {
    throw new AuthorizationError('You do not have access to this attachment');
  }

  await attachmentStorage.assertExists(attachment.storagePath);

  return {
    attachment,
    absolutePath: attachmentStorage.resolveAbsolutePath(attachment.storagePath),
  };
};

const createListLoanAlerts = ({ alertRepository, loanAccessPolicy, loanViewService }) => async ({ actor, loanId }) => {
  const loan = await loanAccessPolicy.findAuthorizedLoan({ actor, loanId });
  return alertRepository.listByLoan(loan.id);
};

const createGetPaymentCalendar = ({ alertRepository, loanAccessPolicy, loanViewService }) => async ({ actor, loanId }) => {
  const loan = await loanAccessPolicy.findAuthorizedLoan({ actor, loanId });
  const { schedule, snapshot } = loanViewService.getCanonicalLoanView(loan);
  const alerts = await alertRepository.listByLoan(loan.id);

  return {
    loanId: loan.id,
    entries: buildCalendarEntries({ schedule, alerts }),
    snapshot,
    alerts,
  };
};

const createGetPayoffQuote = ({ loanAccessPolicy, loanViewService }) => async ({ actor, loanId, asOfDate }) => {
  const loan = await loanAccessPolicy.findAuthorizedLoan({ actor, loanId });

  return loanViewService.getPayoffQuote(loan, asOfDate);
};

const createExecutePayoff = ({ loanAccessPolicy, paymentApplicationService, clock = () => new Date() }) => async ({ actor, loanId, asOfDate, quotedTotal }) => {
  if (actor?.role !== 'customer') {
    throw new AuthorizationError('Only customers can execute payoff payments');
  }

  const loan = await loanAccessPolicy.findAuthorizedLoan({ actor, loanId });

  return paymentApplicationService.applyPayoff({
    loanId: loan.id,
    asOfDate,
    quotedTotal,
    paymentDate: clock(),
  });
};

const createListPromisesToPay = ({ promiseRepository, loanAccessPolicy }) => async ({ actor, loanId }) => {
  const loan = await loanAccessPolicy.findAuthorizedLoan({ actor, loanId });
  return promiseRepository.expireBrokenPromises({ loanId: loan.id });
};

const createCreatePromiseToPay = ({ promiseRepository, loanAccessPolicy }) => async ({ actor, loanId, payload }) => {
  if (!['admin', 'agent'].includes(actor.role)) {
    throw new AuthorizationError('Only admins and agents can create promises to pay');
  }

  const loan = await loanAccessPolicy.findAuthorizedMutationLoan({ actor, loanId });
  const promisedDate = new Date(payload.promisedDate);
  if (Number.isNaN(promisedDate.getTime())) {
    throw new ValidationError('Promised date is required');
  }

  const amount = Number(payload.amount);
  if (!Number.isFinite(amount) || amount <= 0) {
    throw new ValidationError('Promise amount must be greater than 0');
  }

  const now = new Date();
  const statusHistory = [{
    status: 'pending',
    changedAt: now.toISOString(),
    actorId: actor.id,
  }];

  return promiseRepository.create({
    loanId: loan.id,
    createdByUserId: actor.id,
    promisedDate,
    amount,
    status: 'pending',
    notes: payload.notes ? String(payload.notes).trim() : null,
    statusHistory,
    lastStatusChangedAt: now,
  });
};

const createDownloadPromiseToPay = ({ promiseRepository, loanAccessPolicy }) => async ({ actor, loanId, promiseId }) => {
  if (!['admin', 'agent'].includes(actor.role)) {
    throw new AuthorizationError('Only admins and agents can download promise documents');
  }

  const loan = await loanAccessPolicy.findAuthorizedLoan({ actor, loanId });
  const promise = await promiseRepository.findByIdForLoan({ loanId: loan.id, promiseId });

  if (!promise) {
    throw new NotFoundError('Promise to pay');
  }

  const customer = loan.Customer || await promiseRepository.getCustomerForPromise(promise.id);

  return {
    fileName: `promise-to-pay-${promise.id}.pdf`,
    contentType: 'application/pdf',
    buffer: buildPromiseToPayPdfBuffer({ promise, loan, customer }),
  };
};

module.exports = {
  createListLoans,
  createCreateSimulation,
  createGetLoanById,
  createCreateLoan,
  createListLoansByCustomer,
  createListLoansByAgent,
  createUpdateLoanStatus,
  createAssignAgent,
  createUpdateRecoveryStatus,
  createDeleteLoan,
  createListLoanAttachments,
  createCreateLoanAttachment,
  createDownloadLoanAttachment,
  createListLoanAlerts,
  createGetPaymentCalendar,
  createGetPayoffQuote,
  createExecutePayoff,
  createListPromisesToPay,
  createCreatePromiseToPay,
  createDownloadPromiseToPay,
};
